export const APP_STORE_COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "BR", name: "Brazil" },
  { code: "IN", name: "India" },
  { code: "MX", name: "Mexico" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "NL", name: "Netherlands" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "RU", name: "Russia" },
  { code: "PL", name: "Poland" },
  { code: "TR", name: "Turkey" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "AE", name: "UAE" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "ID", name: "Indonesia" },
  { code: "MY", name: "Malaysia" },
  { code: "SG", name: "Singapore" },
  { code: "PH", name: "Philippines" },
  { code: "TW", name: "Taiwan" },
  { code: "HK", name: "Hong Kong" },
];

export const APP_STORE_GENRES = [
  { value: "", label: "All Genres" },
  { value: "BOOKS", label: "Books" },
  { value: "BUSINESS", label: "Business" },
  { value: "DEVELOPER_TOOLS", label: "Developer Tools" },
  { value: "EDUCATION", label: "Education" },
  { value: "ENTERTAINMENT", label: "Entertainment" },
  { value: "FINANCE", label: "Finance" },
  { value: "FOOD_AND_DRINK", label: "Food & Drink" },
  { value: "GAMES", label: "Games" },
  { value: "GRAPHICS_AND_DESIGN", label: "Graphics & Design" },
  { value: "HEALTH_AND_FITNESS", label: "Health & Fitness" },
  { value: "LIFESTYLE", label: "Lifestyle" },
  { value: "MAGAZINES_AND_NEWSPAPERS", label: "Magazines & Newspapers" },
  { value: "MEDICAL", label: "Medical" },
  { value: "MUSIC", label: "Music" },
  { value: "NAVIGATION", label: "Navigation" },
  { value: "NEWS", label: "News" },
  { value: "PHOTO_AND_VIDEO", label: "Photo & Video" },
  { value: "PRODUCTIVITY", label: "Productivity" },
  { value: "REFERENCE", label: "Reference" },
  { value: "SHOPPING", label: "Shopping" },
  { value: "SOCIAL_NETWORKING", label: "Social Networking" },
  { value: "SPORTS", label: "Sports" },
  { value: "TRAVEL", label: "Travel" },
  { value: "UTILITIES", label: "Utilities" },
  { value: "WEATHER", label: "Weather" },
];
